sonar.projectKey=master-gateway-backend
sonar.projectName=Master Gateway Backend
sonar.projectVersion=1.0
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.exclusions=**/*MapperImpl.java
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.host.url=http://localhost:9000
sonar.token=sqa_bb2946eaf3d8a90e8b4b5c022faa079812d760f6
